### ISSUE TITLE
错误: The system cannot find the file specified.

### ISSUE THREAD

**Issue by Ailiaote** [gizmo-ds/vcc-auto-translate#1]
VCC Auto Translate 安装程序

此安装程序将向您的 VCC 安装添加 VCC Auto Translate 脚本。
源代码：https://github.com/gizmo-ds/vcc-auto-translate

错误: The system cannot find the file specified.
按回车键退出...

不清楚是什么原因...

**Comment by gizmo-ds** [comment]
应该是没寻找到VCC的安装目录
可以尝试将安装程序放到VCC安装目录下执行 (与 `CreatorCompanion.exe` 同目录)
